import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverComponentsExternalPackages: [
    "@mastra/core",
    "@mastra/memory",
    "@mastra/pinecone",
    "@mastra/rag",
    "@mastra/upstash",
    "@mastra/vector-pinecone",
    "@mastra/voice-elevenlabs",
    "@mastra/voice-google",
    "@mastra/loggers",
    "@agentic/core",
    "@agentic/mastra",
    "@agentic/ai-sdk",
    "@agentic/langchain",
    "@agentic/mcp",
    "@agentic/stdlib",
    "@agentic/exa",
    "@agentic/google-custom-search",
    "@agentic/arxiv",
    "@agentic/tavily",
    "@agentic/wikipedia",
    "@agentic/firecrawl",
    "@agentic/genkit",
    "@ai-sdk/google",
    "@ai-sdk/google-vertex",
    "@ai-sdk/provider",
    "@pinecone-database/pinecone",
    "langchain",
    "@langchain/community",
    "@langchain/google-genai",
    "@langchain/pinecone",
    "langsmith",
    "langfuse",
    "firebase-admin",
    "@modelcontextprotocol/sdk",
    "exa-js",
    "ai",
    "@ai-sdk/anthropic",
    "@ai-sdk/openai",
    "@langchain/core",
    "llamaindex",
    "@google/generative-ai",
    "@langchain/openai",
    "p-throttle",
    "@langchain/anthropic",
    "@agentic/github",
    "@agentic/openapi-to-ts",
    "@agentic/notion",
    "@agentic/bing",
    "@agentic/jina",
    "@agentic/reddit",
    "@agentic/searxng",
    "@agentic/serper",
    "@agentic/social-data",
    "@agentic/wikidata",
    "@agentic/wolfram-alpha",
    "@mastra/vectorize",
    "@mastra/pg",
    "@mastra/clickhouse",
    "@mastra/github",
  ],
  output: "export",
  images: { unoptimized: true },
  pageExtensions: ["ts", "tsx"],
  reactStrictMode: true,
  experimental: {
    mdxRs: true,
  },
};

export default nextConfig;
